name: Publish Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      CONTAINER_NAME: ${{ github.event.repository.name }}

    steps:
    - uses: actions/checkout@v2
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Prepare
      run: echo "CONTAINER_VERSION::$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
    - name: Build
      run: docker build . --target build --file ./build/Dockerfile --tag $CONTAINER_NAME:$CONTAINER_VERSION --tag $CONTAINER_NAME:latest
